version: "3.9"

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports: 
      - "8080:80"
    links:
      - backend
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app