version: "3.9"

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    ports: 
      - "5173:5173"
    networks:
      - backend
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - backend
networks:
  backend: